name: Tests

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest numpy

      - name: Run unit tests
        env:
          OPENAI_API_KEY: test  # Mock API key for unit tests
        run: |
          # Run unit tests (all tests except integration/)
          python -m unittest discover -s tests -p "test_*.py" -v
          
  integration-tests:
    needs: unit-tests  # Only run if unit tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest numpy optillm

      - name: Start optillm server
        run: |
          echo "Starting optillm server for integration tests..."
          OPTILLM_API_KEY=optillm optillm --model google/gemma-3-270m-it --port 8000 &
          echo $! > server.pid
          
          # Wait for server to be ready
          echo "Waiting for server to start..."
          sleep 15
          
          # Test server health
          curl -s http://localhost:8000/health || echo "Server health check failed"
        env:
          OPTILLM_API_KEY: optillm

      - name: Run integration tests
        env:
          OPENAI_API_KEY: optillm
          OPTILLM_API_KEY: optillm
        run: |
          pytest tests/integration -v --tb=short
          
      - name: Stop optillm server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm server.pid
          fi
          pkill -f "optillm.*8000" || true